[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.117.1",
    "pytest>=8.4.2",
    "python-multipart>=0.0.20",
    "uvicorn>=0.37.0",
]
